from enum import Enum

class ModelSetMapping(Enum):
    # Map model set/parameter names to DataClass keys
    N = ("n", ["I", "J", "PF"])
    I = ("i", "I")  # (model_set_name, data_key)
    J = ("j", "J")
    PF = ("pf", "PF")
    T = ("t", "T")
    TT = ("tt", "T")
    # C = ("c", "C")
    D = ("d", "D")
    S = ("s", "S")
    # ARCS = ("arcs", "A")
    PROD = ("Qprod", "PROD")
    # GOR = ("gor", "GOR")
    # WOR = ("wor", "WOR")
    ST_TIME = ("st_time", "START_TIME")
    FAC_CAP = ("capacity", "FAC_CAP")
    DIAM_SIZES = ("diam", "DIAM_SIZES")
    FAC_COST = ("facility_cost_size", "FAC_COST")
    DIAM_COST = ("diameter_cost", "DIAM_COST")
    IR = ("ir", "IR")
    DIST = ("dist", ["DIST_IJ", "DIST_JK"])
    # HFFL = ("hffl", "HFFL")
    PWELL = ("pwell", "PWELL")
    PIN_PF = ("pmin_pf", "P_IN")
